# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('date', models.DateField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField(blank=True, null=True)),
                ('total', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
